### ISSUE TITLE
Postfix sasl_passwd Berkeley DB Deprecated

### ISSUE THREAD

**Issue by xturavaina** [PHOENIX-MEDIA/docker-nginx-php#3]
Hi,

Berkeley DB was deprecated in alpine 3.13 

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#Deprecation_of_Berkeley_DB_.28BDB.29

postmap defaults to lmdb in 3.19 and bin/setup.sh still points to hash.

postmap hash:/etc/postfix/sasl_passwd

a tiny change from:

postconf -e "smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd"

to:

postconf -e "smtp_sasl_password_maps=lmdb:/etc/postfix/sasl_passwd"

should do the trick ;-)

**Comment by phoenix-bjoern** [comment]
@xturavaina Thank you for raising this issue. The changes are applied in the php8.1 and php8.2 branch. New images are available on DockerHub: https://hub.docker.com/r/phoenixmedia/nginx-php/tags.
